
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install llvm 19
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 19
    - name: Install tools
      run: cd tests && make install-all
    - name: Build contract
      run: make all-via-docker
    - name: Run all testcases
      run: cd tests && make all
    - name: Run ckb-auth-cli tests
      run: cd tools/ckb-auth-cli && cargo test
